    nombre = input("ingrese nombre: ")
    print(f"contiene a: {"a" in nombre}")
    print(f"contiene e: {"e" in nombre}")
    print(f"contiene i: {"i" in nombre}")
    print(f"contiene o: {"o" in nombre}")
    print(f"contiene u: {"u" in nombre}")

    nombre = input("ingrese nombre: ")
    print(f"contiene a: {"a" in nombre}")
    print(f"contiene e: {"e" in nombre}")
    print(f"contiene i: {"i" in nombre}")
    print(f"contiene o: {"o" in nombre}")
    print(f"contiene u: {"u" in nombre}")
